# Generated by Django 2.2.2 on 2019-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_resource_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='first_name',
            new_name='nick_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='last_name',
        ),
        migrations.AddField(
            model_name='subactivity',
            name='name',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
