# Generated by Django 2.2.2 on 2019-06-30 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0003_auto_20190615_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Project'),
        ),
    ]
