# Generated by Django 2.2.2 on 2019-07-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_auto_20190630_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='feature',
        ),
        migrations.AddField(
            model_name='activity',
            name='feature',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimator.Feature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estimate',
            name='phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estimator.Phase'),
            preserve_default=False,
        ),
    ]
