# Generated by Django 2.2.2 on 2019-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0005_auto_20190706_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
