# Generated by Django 2.2.2 on 2019-07-06 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0006_auto_20190706_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phase_manager', to='estimator.Resource'),
            preserve_default=False,
        ),
    ]
