# Generated by Django 2.2.2 on 2019-08-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0012_auto_20190810_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('1', 'Backlog'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'On Hold')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subactivity',
            name='status',
            field=models.CharField(choices=[('1', 'Backlog'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'On Hold')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
