# Generated by Django 2.2.2 on 2019-08-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0013_auto_20190811_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='estimated_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subactivity',
            name='estimated_time',
            field=models.FloatField(default=0),
        ),
    ]
