# Generated by Django 2.2.2 on 2019-08-18 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0014_auto_20190817_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActivityWorkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worked_hours', models.FloatField(default=0)),
                ('note', models.CharField(default='', max_length=10000)),
                ('sub_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.SubActivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityWorkEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worked_hours', models.FloatField(default=0)),
                ('note', models.CharField(default='', max_length=10000)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Activity')),
            ],
        ),
    ]
