# Generated by Django 2.2.2 on 2019-08-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0015_activityworkentry_subactivityworkentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityworkentry',
            name='note',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='subactivityworkentry',
            name='note',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
