# Generated by Django 2.2.2 on 2019-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0016_auto_20190818_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityworkentry',
            name='note',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='subactivityworkentry',
            name='note',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
