# Generated by Django 2.2.2 on 2019-10-05 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0017_auto_20190818_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='manager',
        ),
    ]
