# Generated by Django 2.2.2 on 2019-10-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0018_remove_phase_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='managers',
            field=models.ManyToManyField(related_name='phase_managers', to='estimator.Resource'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='resources',
            field=models.ManyToManyField(related_name='phase_resources', to='estimator.Resource'),
        ),
    ]
