# Generated by Django 2.2.2 on 2019-10-20 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0019_auto_20191005_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('1', 'View'), ('2', 'Edit')], max_length=1)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Estimate')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimator.Resource')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='resources',
            field=models.ManyToManyField(related_name='estimate_resources', through='estimator.EstimateResources', to='estimator.Resource'),
        ),
    ]
