# Generated by Django 2.2.2 on 2019-11-02 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0021_auto_20191020_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstimateResources',
            new_name='EstimateResource',
        ),
    ]
