# Generated by Django 2.2.2 on 2019-11-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0022_auto_20191102_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.Resource'),
        ),
        migrations.AlterField(
            model_name='subactivity',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.Resource'),
        ),
    ]
