# Generated by Django 2.2.2 on 2019-11-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0024_auto_20191102_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityworkentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.Resource'),
        ),
        migrations.AddField(
            model_name='subactivityworkentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estimator.Resource'),
        ),
    ]
