# Generated by Django 2.2.2 on 2019-11-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0025_auto_20191103_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Backlog'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'On Hold')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Backlog'), ('2', 'In Progress'), ('3', 'Completed'), ('4', 'On Hold')], max_length=1, null=True),
        ),
    ]
