# Generated by Django 2.2.2 on 2019-11-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0026_auto_20191109_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
